services:
  - type: web
    name: codolio-backend
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend          # important for monorepo
    dockerfilePath: ./Dockerfile
    # healthCheckPath: /actuator/health
    envVars:
      - key: CORS_ORIGIN
        value: "*"            # change later to your Vercel URL